dj004/dj004/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ocrTest.urls'))
]

dj004/ocrTest/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from .views import *

#이미지 업로드
from django.conf.urls.static import static
from django.conf import settings

app_name = 'ocrTest'      #app namespace 

urlpatterns = [
    path('', index, name='index'),
    path('rank/', rank, name='rank'),
    path('get_rank/', get_rank, name='get_rank'),
    path('save/', save, name='save'),
    path('ocr/', ocr, name='ocr'),
    # path('ocrAPI/', ocrAPI, name='ocrAPI'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', signup, name='signup'),
    path('imgs/', ImgView.as_view(), name='imgs'),
    path('ranklist/', ranklist, name='ranklist'),
    # path(r'^(?P<year>[0-9]{4}/?P<month>[0-9]{2}/?P<date>[0-9]{2}/rankingdetail/', RankingDetailView.as_view(), name='rankingdetail'),
    path('rankdetail/<year>/<month>/<date>/', rankdetail, name='rankdetail'),
]


##이미지 url 설정 (MEDIA_URL로 들어오는 요청에 대해 MEDIA_ROOT 경로 탐색)
if settings.DEBUG:   #settings.DEBUG가 false 일시 빈리스트를 반환(명시적 표시를 위해 작성)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    #runserver명령을 통해 구동하는 개발서버에서는 media파일 자동으로 서빙해주지않음

dj004/ocrTest/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
  mainphoto = models.ImageField(blank=True, null=True, upload_to='')  
  photoname = models.CharField(max_length=50)

  def __str__(self):
    return self.mainphoto  

class Ranking(models.Model):
  pub_date = models.DateTimeField("data published...")
  title = models.CharField(max_length=100)
  image = models.ImageField(blank=True, null=True, upload_to='rank')
  start_date = models.DateField()         #시작 날짜
  end_date = models.DateField()           #끝 날짜
  place = models.CharField(max_length=30)
  ranking = models.CharField(max_length=10)
  
  def __str__(self):
    return self.title
  
  

dj004/ocrTest/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
  email = forms.EmailField(label="이메일")
  
  class Meta: 
    model = User
    fields = ("username", "password1", "password2", "email")

dj004/ocrTest/views.py
from django.utils import timezone
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.urls import resolve
from django.views import generic
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.views.decorators.csrf import csrf_exempt

from .models import  Post, Ranking
from django.views import generic
from .forms import UserForm
from .semi_crawler import *

import datetime
import requests
import json


class ImgView(generic.ListView):
  model = Post
  
  template_name = 'ocrTest/imglist.html'     #템플릿 파일 위치 지정
  context_object_name = 'images'      #템플릿파일로 넘겨주는 객체리스트 이름지정 : html파일에서 설정한 이름으로 객체를 가져올 수 있다..!!
  paginate_by: 5      #한페이지에 보여줄 객체의 개수   (페이징)
  
def ranklist(request):
  date_list = list(Ranking.objects.dates("pub_date", "day"))
  
  return render(request, 'ocrTest/ranklist.html',{'date_list':date_list})
  
# #* 오늘 크롤링한 랭킹 데이터만 보여준다.
# class RankingDetailView(generic.DetailView):  
#   model = Ranking
  
#   template_name = 'ocrTest/rankdetail.html'
  
  
#   def get_ranking_queryset(self):         #해당날짜의 최신 50개 정보(50위까지) 가져오기 
#     # date : 2022-08-06 형식
#     print("TESTESETESTESTESTSETESTESETESTESTESTSETESTESETESTESTESTSE")
#     current_url = resolve(self.request.path_info).url_name
    
#     print("date : ",current_url)
#     date = current_url.split("/")
#     year = date[0]
#     month = date[1]
#     day = date[2]
  
#     t_date = datetime.date(year, month, day)
#     ranking_list = Ranking.objects.exclude(
#         pub_date = t_date
#         ).order_by('pub_date')[:50]
    
#     return  ranking_list
      
#* 오늘 크롤링한 랭킹 데이터만 보여준다.
def rankdetail(request, year, month, date):  
  print("TESTESETESTESTESTSETESTESETESTESTESTSETESTESETESTESTESTSE", year, month, date)
  model = Ranking
  
  #해당날짜의 최신 50개 정보(50위까지) 가져오기 
  # date : 2022-08-06 형식
  
  # print("date : ",current_url)
  # date = current_url.split("/")
  
  year = int(year)
  month = int(month)
  date = int(date)

  t_date = datetime.date(year, month, date)
  
  print("날짜 확인 :   ", t_date)
  
  ranking_list = reversed(Ranking.objects.filter(
      pub_date__startswith = t_date
      ).order_by("-pub_date")[:50])       #내림차순으로 정렬
  
  print("ranking_list : ", ranking_list)
  
  return render(request,  'ocrTest/rankdetail.html', {"ranking_list" : ranking_list})
      

##후에 api로 ocr 결과 받아주는걸로 변경(사진 저장X)
def ocr(request):
  print("request",request)
  # print("request_dir",dir(request))
  print("request.method: ", request.method)
  if request.method =="POST":
      print("POST request")
      try:
        new_photo = request.POST['file']
        print("new_photo-------",new_photo)
      
        return render(request, 'ocrTest/ocr.html', {'mainphoto':new_photo})
      
      except:
  
        print("post-------",request.POST)
        # data = request.body
        # print("data-------",data)
        
        if request.FILES['file']:
          print("FILES request")
          new_photo = Post.objects.create(
            # postname=request.POST['photoname'],
            mainphoto=request.FILES['file']
          )
          print("image: ", request.FILES['file'])
  else:
    return render(request,'ocrTest/ocr.html')
  
  return render(request, 'ocrTest/ocr.html', {'mainphoto': request.FILES['file']})

def rank(request):
  
  return render(request, 'ocrTest/rank.html')


def get_rank(request):
  try:
    driver = run()
    ranking_info= run_browser(driver)
    json_rank_info = json.dumps(ranking_info, indent=4, ensure_ascii= False)
    print(json_rank_info)
  except(Exception)  :
    print("except-------------------------")
    return render(request, 'ocrTest/rank.html', {'ranking_info': "ERROR_ERROR_ERROR"})
  print("http Response=---------")
  return HttpResponse(json_rank_info, content_type = "application/json")

def ocrAPI(request):
  url = "http://61.72.55.130:8999/ocr/imgUploadMulti"
  if request.method =="POST":
    form_data = request.POST
    print('form_data:', form_data)
    dict_data = form_data.dict()
    print('dict_data:', dict_data)
    json_data = json.dumps(dict_data)
    print('json_data_af:', json_data)
    
    file = dict_data['file']     #이미지데이터보내기(인코딩)
    ocrmode = dict_data['ocrmode']
    metaId = dict_data['metaId']
    docModelId = dict_data['docModelId']
    
    print("file : %s, ocrmode : %s" % (file, ocrmode))
    ocr_res = requests.post(url, json=json_data)
    print("ocr_res : ", ocr_res)
    header = {}
    return render(request, 'ocrTest/ocr.html', {'ocr-result' : ocr_res})
  
  
  return render(request, 'ocrTest/ocr.html')
        

# @csrf_exempt
def save(request):
  print("save-------------------------")
  if request.method == "POST":
    data = request.body
    json_data = json.loads(data)
    
    print(json_data)
    data_len = len(list(json_data.keys()))
    for i in range(data_len):
      idx = str(i)
      date = json_data[idx]['date'].replace('.', '-')
      
      new_data = Ranking.objects.create(
        pub_date = timezone.now()
        ,title = json_data[idx]['title']
        ,image = json_data[idx]['image']
        ,place = json_data[idx]['place']
        ,start_date = date.split('~')[0]
        ,end_date = date.split('~')[1]
        ,ranking = json_data[idx]['ranking']
      )
      
    print("POST 테스트입니다!!!!!!!!!!!!!!")
    return redirect('/rank/')
    
  return render(request, 'ocrTest/rank.html')
    
    
  
def index(request):
  return render(request, 'index.html')


# def login(request):
#   if request.method == 'POST':
    
#     return render(request, 'ocrTest/index.html')
    
#   else :    #get request시 
    
#     return render(request, 'ocrTest/login.html')
    
    
    

def signup(request):
  if request.method == "POST":     #POST요청일 시, 화면에서 입력한 데이터로 사용자 생성
    form  = UserForm(request.POST)
    if form.is_valid():    #form값 유효성 확인
      form.save()
      username = form.cleaned_data.get('username')          
      raw_password = form.cleaned_data.get('password1')      #form의 입력값 개별적으로 얻고 싶은경우 사용
      user = authenticate(username=username, password=raw_password) #사용자 인증담당(사용자명, 비밀번호 검증)
      auth_login(request, user)  #로그인 담당(사용자 세션을 생성한다.)
      return redirect('/')
  else:       #GET 요청일 시, 회원가입 화면 보여준다.
    form = UserForm()
  return render(request, 'user/signup.html', {'form': form})
  
  

dj004/ocrTest/templates/user/form_errors.html
<!-- users>form_errors.html -->

{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<!-- 필드 오류를 출력한다. -->
<div>
  <strong>{{ field.label }}</strong>
  {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<!-- 넌필드 오류를 출력한다. -->
<div>
  <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

dj004/ocrTest/templates/user/login.html
{% extends "index.html" %}

{% block contents %}
<main class="login-form">
  <div class="cotainer">
      <div class="row justify-content-center">
          <div class="col-md-8">
              <div class="card">
                  <div class="card-header">Register</div>
                  <div class="card-body">
                      <form method="post" action="{% url 'ocrTest:login' %}">
                        {% include 'user/form_errors.html' %}
                        {% csrf_token %}
                          <div class="form-group row">
                              <label for="username" class="col-md-4 col-form-label text-md-right">ID</label>
                              <div class="col-md-6">
                                  <input type="text" id="username" class="form-control" name="username" required autofocus>
                              </div>
                          </div>

                          <div class="form-group row">
                              <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                              <div class="col-md-6">
                                  <input type="password" id="password" class="form-control" name="password" required>
                              </div>
                          </div>

                          <div class="form-group row">
                              <div class="col-md-6 offset-md-4">
                                  <div class="checkbox">
                                      <label>
                                          <input type="checkbox" name="remember"> Remember Me
                                      </label>
                                  </div>
                              </div>
                          </div>

                          <div class="col-md-6 offset-md-4">
                              <button type="submit" class="btn btn-primary">
                                  Register
                              </button>
                              <a href="#" class="btn btn-link">
                                  기억이...전혀....
                              </a>
                          </div>
                  </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
  </div>

</main>
{% endblock %}

dj004/ocrTest/templates/user/signup.html
{% extends "index.html" %}
{% block contents %}
<div class="container my-3" style="max-width:30%; padding-top: 3%;">
  <form method="post" action="{% url 'ocrTest:signup' %}">
      {% csrf_token %}
      {% include "user/form_errors.html" %}
      <div class="mb-3">
          <label for="username">사용자 이름</label>
          <input type="text" class="form-control" name="username" id="username"
                 value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="mb-3">
          <label for="password1">비밀번호</label>
          <input type="password" class="form-control" name="password1" id="password1"
                 value="{{ form.password1.value|default_if_none:'' }}">
      </div>
      <div class="mb-3">
          <label for="password2">비밀번호 확인</label>
          <input type="password" class="form-control" name="password2" id="password2"
                 value="{{ form.password2.value|default_if_none:'' }}">
      </div>
      <div class="mb-3">
          <label for="email">이메일</label>
          <input type="text" class="form-control" name="email" id="email"
                 value="{{ form.email.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">생성하기</button>
  </form>
</div>
{% endblock %}